package poo;

import BD.AccessDBConnection;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.table.DefaultTableModel;
import pack1.Alumnos;
import pack1.Datos;
import pack1.Personal;
import pack1.HistorialClinico;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class Consultas extends javax.swing.JFrame
{

    public static ArrayList<String[]> Persona = new ArrayList<>();

    /**
     * Creates new form Consultas
     */
    public Consultas()
    {

        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pesta = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnElimina = new javax.swing.JToggleButton();
        CveRegistro1 = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        Cancelar3 = new javax.swing.JButton();
        jcbxMuestraT = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        btnElimina1 = new javax.swing.JToggleButton();
        btnBuscarC1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        cbxFrecuencia = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        cbxEstatus = new javax.swing.JComboBox<>();
        cbxCarreras = new javax.swing.JComboBox<>();
        jcbxDiabetes = new javax.swing.JCheckBox();
        jcbxAlergias = new javax.swing.JCheckBox();
        jcbxDesnutricion = new javax.swing.JCheckBox();
        jcbxObesidad = new javax.swing.JCheckBox();
        jcbxSobrepeso = new javax.swing.JCheckBox();
        jcbxOtras = new javax.swing.JCheckBox();
        jcbxSelecTodos = new javax.swing.JCheckBox();
        Cancelar4 = new javax.swing.JButton();
        cbxViveCon = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelPT = new javax.swing.JLabel();
        tituloA = new javax.swing.JLabel();
        titulaoMe = new javax.swing.JLabel();
        tituloPlan = new javax.swing.JLabel();
        tituloP = new javax.swing.JLabel();
        labelP = new javax.swing.JLabel();
        labelAntece = new javax.swing.JLabel();
        labelM = new javax.swing.JLabel();
        CveRegistro = new javax.swing.JTextField();
        labelSegAp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelAp = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCitas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesta.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        pesta.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cve", "Nombre", "Primer Apellido", "Segundo Apelido", "Sexo", "Alergias", "Desnutricion", "Diabetes", "Obesidad", "Sobrepeso", "Otros", "No.consultas M"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabla.setOpaque(false);
        tabla.setRequestFocusEnabled(false);
        tabla.setShowGrid(false);
        tabla.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tablaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabla);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 430));

        jScrollPane3.setViewportView(jPanel2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 980, 450));

        btnElimina.setText("Eliminar registro");
        btnElimina.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel1.add(btnElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 130, 30));

        CveRegistro1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CveRegistro1ActionPerformed(evt);
            }
        });
        CveRegistro1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                CveRegistro1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CveRegistro1KeyTyped(evt);
            }
        });
        jPanel1.add(CveRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 240, 30));

        btnBuscarC.setText("Buscar");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 80, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Búsqueda");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnCancelar.setText("Volver");
        btnCancelar.setActionCommand("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, -140, 80, 40));

        Cancelar3.setText("Cerrar");
        Cancelar3.setActionCommand("");
        Cancelar3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar3ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 90, 40));

        jcbxMuestraT.setBackground(new java.awt.Color(0, 0, 51));
        jcbxMuestraT.setForeground(new java.awt.Color(255, 255, 255));
        jcbxMuestraT.setText("Mostrar todo");
        jcbxMuestraT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxMuestraTActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxMuestraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 130, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cve", "Nombre", "Primer Apellido", "Segundo Apelido", "Sexo", "Alergias", "Desnutricion", "Diabetes", "Obesidad", "Sobrepeso", "Otros", "No.consultas M"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabla1.setOpaque(false);
        tabla1.setRequestFocusEnabled(false);
        tabla1.setShowGrid(false);
        tabla1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tabla1KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tabla1);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 430));

        jScrollPane5.setViewportView(jPanel6);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 980, 450));

        btnElimina1.setText("Eliminar registro");
        btnElimina1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnElimina1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnElimina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 130, 30));

        btnBuscarC1.setText("Buscar");
        btnBuscarC1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarC1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 80, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Búsqueda");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnCancelar1.setText("Volver");
        btnCancelar1.setActionCommand("");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, -140, 80, 40));

        cbxFrecuencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frecuencia", "Mayor F.M", "Menor F.M" }));
        cbxFrecuencia.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxFrecuenciaItemStateChanged(evt);
            }
        });
        cbxFrecuencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxFrecuenciaActionPerformed(evt);
            }
        });
        jPanel4.add(cbxFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "Hombre", "Mujer" }));
        cbxSexo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxSexoItemStateChanged(evt);
            }
        });
        cbxSexo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxSexoActionPerformed(evt);
            }
        });
        jPanel4.add(cbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 30));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus", "Base", "Temporal" }));
        cbxEstatus.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxEstatusItemStateChanged(evt);
            }
        });
        cbxEstatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxEstatusActionPerformed(evt);
            }
        });
        jPanel4.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 100, 30));

        cbxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carreras", "LISW", "LIP", "LSC", "LIPI", "LIM", "LIC" }));
        cbxCarreras.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxCarrerasItemStateChanged(evt);
            }
        });
        cbxCarreras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxCarrerasActionPerformed(evt);
            }
        });
        jPanel4.add(cbxCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 100, 30));

        jcbxDiabetes.setBackground(new java.awt.Color(0, 0, 51));
        jcbxDiabetes.setForeground(new java.awt.Color(255, 255, 255));
        jcbxDiabetes.setText("Diabetes");
        jcbxDiabetes.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxDiabetesItemStateChanged(evt);
            }
        });
        jcbxDiabetes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxDiabetesActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxDiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, 20));

        jcbxAlergias.setBackground(new java.awt.Color(0, 0, 51));
        jcbxAlergias.setForeground(new java.awt.Color(255, 255, 255));
        jcbxAlergias.setText("Alergias");
        jcbxAlergias.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxAlergiasItemStateChanged(evt);
            }
        });
        jcbxAlergias.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jcbxAlergiasStateChanged(evt);
            }
        });
        jcbxAlergias.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxAlergiasActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        jcbxDesnutricion.setBackground(new java.awt.Color(0, 0, 51));
        jcbxDesnutricion.setForeground(new java.awt.Color(255, 255, 255));
        jcbxDesnutricion.setText("Desnutrición");
        jcbxDesnutricion.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxDesnutricionItemStateChanged(evt);
            }
        });
        jcbxDesnutricion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxDesnutricionActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxDesnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 20));

        jcbxObesidad.setBackground(new java.awt.Color(0, 0, 51));
        jcbxObesidad.setForeground(new java.awt.Color(255, 255, 255));
        jcbxObesidad.setText("Obesidad");
        jcbxObesidad.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxObesidadItemStateChanged(evt);
            }
        });
        jcbxObesidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxObesidadActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxObesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, 20));

        jcbxSobrepeso.setBackground(new java.awt.Color(0, 0, 51));
        jcbxSobrepeso.setForeground(new java.awt.Color(255, 255, 255));
        jcbxSobrepeso.setText("Sobrepeso");
        jcbxSobrepeso.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxSobrepesoItemStateChanged(evt);
            }
        });
        jcbxSobrepeso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxSobrepesoActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxSobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, 20));

        jcbxOtras.setBackground(new java.awt.Color(0, 0, 51));
        jcbxOtras.setForeground(new java.awt.Color(255, 255, 255));
        jcbxOtras.setText("Otras ");
        jcbxOtras.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jcbxOtrasItemStateChanged(evt);
            }
        });
        jcbxOtras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxOtrasActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxOtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, 20));

        jcbxSelecTodos.setBackground(new java.awt.Color(0, 0, 51));
        jcbxSelecTodos.setForeground(new java.awt.Color(255, 255, 255));
        jcbxSelecTodos.setText("Todos los filtros");
        jcbxSelecTodos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbxSelecTodosActionPerformed(evt);
            }
        });
        jPanel4.add(jcbxSelecTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 130, -1));

        Cancelar4.setText("Cerrar");
        Cancelar4.setActionCommand("");
        Cancelar4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar4ActionPerformed(evt);
            }
        });
        jPanel4.add(Cancelar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 90, 40));

        cbxViveCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vive Con", "Padre", "Madre", "Ambos" }));
        cbxViveCon.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxViveConItemStateChanged(evt);
            }
        });
        cbxViveCon.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxViveConActionPerformed(evt);
            }
        });
        jPanel4.add(cbxViveCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 100, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pesta.addTab("Consultas Generales", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPT.setForeground(new java.awt.Color(51, 51, 51));
        labelPT.setText("Plan de T");
        labelPT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(labelPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 680, 60));

        tituloA.setText("Antecedentes ");
        jPanel5.add(tituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 500, 20));

        titulaoMe.setText("Medicamento");
        jPanel5.add(titulaoMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 500, 20));

        tituloPlan.setText("Plan de tratamiento");
        jPanel5.add(tituloPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 500, 20));

        tituloP.setBackground(new java.awt.Color(255, 255, 255));
        tituloP.setText("Padecimiento");
        jPanel5.add(tituloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 490, 20));

        labelP.setForeground(new java.awt.Color(51, 51, 51));
        labelP.setText("Padecimiento");
        labelP.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(labelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 680, 60));

        labelAntece.setForeground(new java.awt.Color(51, 51, 51));
        labelAntece.setText("Antecedentes");
        labelAntece.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(labelAntece, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 680, 70));

        labelM.setForeground(new java.awt.Color(51, 51, 51));
        labelM.setText("Medicamento");
        labelM.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(labelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 680, 70));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 710, 490));

        CveRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CveRegistroActionPerformed(evt);
            }
        });
        CveRegistro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                CveRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CveRegistroKeyTyped(evt);
            }
        });
        jPanel3.add(CveRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 290, 30));

        labelSegAp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSegAp.setForeground(new java.awt.Color(255, 255, 255));
        labelSegAp.setText("SApellido");
        jPanel3.add(labelSegAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 100, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Búsqueda");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        labelNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNom.setForeground(new java.awt.Color(255, 255, 255));
        labelNom.setText("Nombre");
        jPanel3.add(labelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, -1));

        labelAp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAp.setForeground(new java.awt.Color(255, 255, 255));
        labelAp.setText("PApellido");
        jPanel3.add(labelAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 90, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 100, 30));

        Cancelar1.setText("Cerrar");
        Cancelar1.setActionCommand("");
        Cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar1ActionPerformed(evt);
            }
        });
        jPanel3.add(Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 80, 40));

        listCitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listCitas.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                listCitasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listCitas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 490));

        pesta.addTab("Consultar citas", jPanel3);

        getContentPane().add(pesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        jcbxMuestraT.setSelected(true);

//        cbxFrecuencia.setVisible(false);
        if (Principal.tipo == 1)
        {

            //reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
            // filtra(Principal.personas, tabla, , WIDTH);
            cbxEstatus.setVisible(false);
        } else
        {
            cbxCarreras.setVisible(false);
            cbxViveCon.setVisible(false);
            //((DefaultTableModel) tabla.getModel()).setRowCount(0);
            //reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
        }
        jcbxMuestraTActionPerformed(null);

        CtrlInterfaz.habilita(false, labelNom, labelAp, labelSegAp, labelP, labelM, labelAntece, labelPT, titulaoMe, tituloA,
                tituloP, tituloPlan);
        //muestra2(Principal.personas, Principal.tipo, );
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void CveRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CveRegistroActionPerformed
    {//GEN-HEADEREND:event_CveRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CveRegistroActionPerformed

    private void CveRegistroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistroKeyPressed
    {//GEN-HEADEREND:event_CveRegistroKeyPressed
        // TODO add your handling code here:
        Validaciones.validaCopyPaste(evt, this, CveRegistro);
        if (evt.getKeyChar() == '\n' && CveRegistro.getText() != null)
        {
            btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_CveRegistroKeyPressed

    private void CveRegistroKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistroKeyTyped
    {//GEN-HEADEREND:event_CveRegistroKeyTyped
        // TODO add your handling code here:
        Validaciones.validaEntero(evt, 7, CveRegistro.getText());
    }//GEN-LAST:event_CveRegistroKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";
        try (Connection conn = DriverManager.getConnection(url))
        {
            if (AccessDBConnection.obtenerTD(conn, CveRegistro.getText(), this, (Principal.tipo == 1 ? "A" : "P")) != null)
            {
                Persona.clear();
                AccessDBConnection.ObtenerHC(conn, Persona, CveRegistro.getText(), (Principal.tipo == 1 ? "A" : "P"));
                if (rootPaneCheckingEnabled)
                {
                    labelNom.setText((Persona.get(0))[1]);
                    labelNom.setVisible(true);
                    labelAp.setText((Persona.get(0))[2]);
                    labelAp.setVisible(true);
                    labelSegAp.setText((Persona.get(0))[3]);
                    labelSegAp.setVisible(true);
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    listModel.clear();
                    listCitas.setModel(listModel);
                    for (int i = 0; i < Persona.size(); i++)
                    {
                        listModel.addElement(Persona.get(i)[9]);
                    }
                    // Crear un JList con el modelo
                    listCitas.setModel(listModel);
                } else
                {
                    Mensajes.error(this, "La clave ingresada no tiene Historial Clinico");
                }
            } else
            {
                Mensajes.error(this, "Clave incorrecta");
            }
        } catch (SQLException e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar1ActionPerformed
    {//GEN-HEADEREND:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_Cancelar1ActionPerformed


    private void listCitasValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_listCitasValueChanged
    {//GEN-HEADEREND:event_listCitasValueChanged
        // TODO add your handling code here:
        if (listCitas.getSelectedIndex() >= 0)
        {
            tituloP.setVisible(true);
            labelP.setVisible(true);
            tituloA.setVisible(true);
            labelAntece.setVisible(true);
            tituloPlan.setVisible(true);
            labelPT.setVisible(true);
            titulaoMe.setVisible(true);
            labelM.setVisible(true);
            labelP.setText(Persona.get(listCitas.getSelectedIndex())[5]);
            labelAntece.setText(Persona.get(listCitas.getSelectedIndex())[6]);
            labelM.setText(Persona.get(listCitas.getSelectedIndex())[7]);
            labelPT.setText(Persona.get(listCitas.getSelectedIndex())[8]);
        }
    }//GEN-LAST:event_listCitasValueChanged

    private void tablaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tablaKeyPressed
    {//GEN-HEADEREND:event_tablaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaKeyPressed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminaActionPerformed
    {//GEN-HEADEREND:event_btnEliminaActionPerformed
        // TODO add your handling code here:

        {

            String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";
            int selectedRow = tabla.getSelectedRow();
            if (selectedRow == -1)
            {
                Mensajes.error(this, "Seleccione una fila para eliminar.");
                return;
            }
            try
            {
                int cve = (Integer) tabla.getValueAt(selectedRow, 0);
                try (Connection conn = DriverManager.getConnection(url))
                {
                    AccessDBConnection.eliminarR(this, conn, cve);
                } catch (SQLException e)
                {
                    e.printStackTrace();
                    Mensajes.error(this, "Error al conectar con la base de datos.");
                }
            } catch (Exception e)
            {
                Mensajes.error(this, "Error al obtener el valor de Cve.");
            }
            filtra();
        }


    }//GEN-LAST:event_btnEliminaActionPerformed
    public void seleccionaMT()
    {

    }
    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarCActionPerformed
    {//GEN-HEADEREND:event_btnBuscarCActionPerformed
        // TODO add your handling code here:
        CtrlInterfaz.habilitaChB(1, false, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxOtras, jcbxSelecTodos, jcbxSobrepeso, jcbxMuestraT);
        cbxCarreras.setSelectedIndex(0);
        cbxEstatus.setSelectedIndex(0);
        cbxFrecuencia.setSelectedIndex(0);
        cbxSexo.setSelectedIndex(0);
        cbxViveCon.setSelectedIndex(0);
        String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";
        try (Connection conn = DriverManager.getConnection(url))
        {
            if (AccessDBConnection.obtenerTD(conn, CveRegistro1.getText(), this, (Principal.tipo == 1 ? "A" : "P")) != null)
            {
                AccessDBConnection.mostrarPersona(conn, "Persona", (Principal.tipo == 1 ? "Alumnos" : "Personal"), CveRegistro1.getText(), tabla);
            } else
            {
                Mensajes.error(this, "Clave incorrecta");
            }
        } catch (SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void CveRegistro1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistro1KeyTyped
    {//GEN-HEADEREND:event_CveRegistro1KeyTyped
        // TODO add your handling code here:
        Validaciones.validaEntero(evt, 7, CveRegistro1.getText());
    }//GEN-LAST:event_CveRegistro1KeyTyped

    private void CveRegistro1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistro1KeyPressed
    {//GEN-HEADEREND:event_CveRegistro1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            btnBuscarCActionPerformed(null);
        }
    }//GEN-LAST:event_CveRegistro1KeyPressed

    private void CveRegistro1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CveRegistro1ActionPerformed
    {//GEN-HEADEREND:event_CveRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CveRegistro1ActionPerformed

    private void Cancelar3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar3ActionPerformed
    {//GEN-HEADEREND:event_Cancelar3ActionPerformed
        dispose();
    }//GEN-LAST:event_Cancelar3ActionPerformed

    private void jcbxMuestraTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxMuestraTActionPerformed
    {//GEN-HEADEREND:event_jcbxMuestraTActionPerformed
        // TODO add your handling code here:
        //((DefaultTableModel) tabla.getModel()).setRowCount(0);

        if (jcbxMuestraT.isSelected())
        {
            CtrlInterfaz.habilita(false, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxOtras, jcbxSelecTodos, jcbxSobrepeso);
            cbxCarreras.setSelectedIndex(0);
            cbxEstatus.setSelectedIndex(0);
            cbxFrecuencia.setSelectedIndex(0);
            cbxSexo.setSelectedIndex(0);
            cbxViveCon.setSelectedIndex(0);
            String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";

            try (Connection conn = DriverManager.getConnection(url))
            {
                AccessDBConnection.mostrarConsulta(conn, "Persona", (Principal.tipo == 1 ? "Alumnos" : "Personal"), tabla);
            } catch (SQLException e)
            {
                e.printStackTrace();
            }

        } else
        {
            ((DefaultTableModel) tabla.getModel()).setRowCount(0);
        }

    }//GEN-LAST:event_jcbxMuestraTActionPerformed

    private void tabla1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tabla1KeyPressed
    {//GEN-HEADEREND:event_tabla1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla1KeyPressed

    private void btnElimina1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnElimina1ActionPerformed
    {//GEN-HEADEREND:event_btnElimina1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnElimina1ActionPerformed

    private void btnBuscarC1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarC1ActionPerformed
    {//GEN-HEADEREND:event_btnBuscarC1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscarC1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelar1ActionPerformed
    {//GEN-HEADEREND:event_btnCancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void cbxFrecuenciaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxFrecuenciaItemStateChanged
    {//GEN-HEADEREND:event_cbxFrecuenciaItemStateChanged
        // TODO add your handling code here:
        jcbxAlergiasActionPerformed(null);
    }//GEN-LAST:event_cbxFrecuenciaItemStateChanged

    private void cbxFrecuenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxFrecuenciaActionPerformed
    {//GEN-HEADEREND:event_cbxFrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFrecuenciaActionPerformed

    private void cbxSexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxSexoItemStateChanged
    {//GEN-HEADEREND:event_cbxSexoItemStateChanged
        // TODO add your handling code here:
        //jcbxAlergiasActionPerformed(null);
        filtra();
    }//GEN-LAST:event_cbxSexoItemStateChanged

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxSexoActionPerformed
    {//GEN-HEADEREND:event_cbxSexoActionPerformed
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_cbxSexoActionPerformed

    private void cbxEstatusItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxEstatusItemStateChanged
    {//GEN-HEADEREND:event_cbxEstatusItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_cbxEstatusItemStateChanged

    private void cbxEstatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxEstatusActionPerformed
    {//GEN-HEADEREND:event_cbxEstatusActionPerformed
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_cbxEstatusActionPerformed

    private void cbxCarrerasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxCarrerasItemStateChanged
    {//GEN-HEADEREND:event_cbxCarrerasItemStateChanged
        // TODO add your handling code here:
        filtra();

        //jcbxAlergiasActionPerformed(null);
    }//GEN-LAST:event_cbxCarrerasItemStateChanged

    private void cbxCarrerasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxCarrerasActionPerformed
    {//GEN-HEADEREND:event_cbxCarrerasActionPerformed
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_cbxCarrerasActionPerformed

    private void jcbxDiabetesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxDiabetesActionPerformed
    {//GEN-HEADEREND:event_jcbxDiabetesActionPerformed
        // TODO add your handling code here:
        filtra();
        //((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxDiabetesActionPerformed

    private void jcbxAlergiasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxAlergiasActionPerformed
    {//GEN-HEADEREND:event_jcbxAlergiasActionPerformed
        // TODO add your handling code here:
        filtra();
        //((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //    reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxAlergiasActionPerformed

    private void jcbxDesnutricionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxDesnutricionActionPerformed
    {//GEN-HEADEREND:event_jcbxDesnutricionActionPerformed
        // TODO add your handling code here:
        filtra();
        //((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxDesnutricionActionPerformed

    private void jcbxObesidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxObesidadActionPerformed
    {//GEN-HEADEREND:event_jcbxObesidadActionPerformed
        // TODO add your handling code here:
        filtra();
        //((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxObesidadActionPerformed

    private void jcbxSobrepesoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxSobrepesoActionPerformed
    {//GEN-HEADEREND:event_jcbxSobrepesoActionPerformed
        // TODO add your handling code here:
        filtra();
        //   ((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //      reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxSobrepesoActionPerformed

    private void jcbxOtrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxOtrasActionPerformed
    {//GEN-HEADEREND:event_jcbxOtrasActionPerformed
        // TODO add your handling code here:
        filtra();
        // ((DefaultTableModel) tabla.getModel()).setRowCount(0);
        //        reporte(Principal.personas, jcbxAlergias, jcbxDesnutricion, jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras, cbxFrecuencia, cbxSexo, cbxCarreras, cbxViveCon, cbxEstatus, tabla, Principal.tipo, Principal.consultas);
    }//GEN-LAST:event_jcbxOtrasActionPerformed

    private void jcbxSelecTodosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbxSelecTodosActionPerformed
    {//GEN-HEADEREND:event_jcbxSelecTodosActionPerformed
        CtrlInterfaz.habilitaChB(1, jcbxSelecTodos.isSelected(), jcbxAlergias, jcbxDesnutricion,
                jcbxDiabetes, jcbxObesidad, jcbxSobrepeso, jcbxOtras);
        CtrlInterfaz.habilita(!jcbxSelecTodos.isSelected(), jcbxMuestraT);
        filtra();

    }//GEN-LAST:event_jcbxSelecTodosActionPerformed

    private void Cancelar4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar4ActionPerformed
    {//GEN-HEADEREND:event_Cancelar4ActionPerformed
        dispose();
    }//GEN-LAST:event_Cancelar4ActionPerformed

    private void cbxViveConActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxViveConActionPerformed
    {//GEN-HEADEREND:event_cbxViveConActionPerformed
        // TODO add your handling code here:
        seleccionaMT();
        filtra();
    }//GEN-LAST:event_cbxViveConActionPerformed

    private void jcbxAlergiasStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jcbxAlergiasStateChanged
    {//GEN-HEADEREND:event_jcbxAlergiasStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxAlergiasStateChanged

    private void cbxViveConItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxViveConItemStateChanged
    {//GEN-HEADEREND:event_cbxViveConItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_cbxViveConItemStateChanged

    private void jcbxAlergiasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxAlergiasItemStateChanged
    {//GEN-HEADEREND:event_jcbxAlergiasItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxAlergiasItemStateChanged

    private void jcbxDesnutricionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxDesnutricionItemStateChanged
    {//GEN-HEADEREND:event_jcbxDesnutricionItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxDesnutricionItemStateChanged

    private void jcbxDiabetesItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxDiabetesItemStateChanged
    {//GEN-HEADEREND:event_jcbxDiabetesItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxDiabetesItemStateChanged

    private void jcbxObesidadItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxObesidadItemStateChanged
    {//GEN-HEADEREND:event_jcbxObesidadItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxObesidadItemStateChanged

    private void jcbxSobrepesoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxSobrepesoItemStateChanged
    {//GEN-HEADEREND:event_jcbxSobrepesoItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxSobrepesoItemStateChanged

    private void jcbxOtrasItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jcbxOtrasItemStateChanged
    {//GEN-HEADEREND:event_jcbxOtrasItemStateChanged
        // TODO add your handling code here:
        filtra();
    }//GEN-LAST:event_jcbxOtrasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {

                new Consultas().setVisible(true);

            }
        });
    }

    private static void muestra(JTable tabla, Datos d, int posReal, int tipoD)
    {

        String[] carreras
                =
                {
                    "", "LISW", "LIP", "LSC", "LIPI", "LIM", "LIC"
                };
        String[] viveC
                =
                {
                    "", "Papa", "Mama", "Ambos"
                };
        int nConsultas = -1;
        if (Principal.consultas != null)
        {
            if (Principal.consultas[posReal] != null)
            {
                nConsultas = Principal.consultas[posReal].length;
            } else
            {
                nConsultas = 0;
            }
        }

        if (d instanceof Alumnos && tipoD == 1)
        {
            DefaultTableModel modelo;
            modelo = (DefaultTableModel) tabla.getModel();
            Object obj[]
                    =
                    {
                        d.getCve(), d.getNom(), d.getPrimerAp(), d.getSegundoAp(), CtrlInterfaz.char_StringCC((d).getSexo(), "Hombre", "Mujer", 'M'),
                        CtrlInterfaz.bolean_String(d.isAlergias()), CtrlInterfaz.bolean_String(d.isDesnutricion()),
                        CtrlInterfaz.bolean_String(d.isDiabetes()), CtrlInterfaz.bolean_String(d.isObesidad()),
                        CtrlInterfaz.bolean_String(d.isSobrepeso()), d.getOtras(), nConsultas, carreras[((Alumnos) d).carrera],
                        viveC[((Alumnos) d).viveCon]
                    };
            modelo.addRow(obj);

        } else
        {
            if (d instanceof Personal && tipoD == 2)
            {
                DefaultTableModel modelo;
                modelo = (DefaultTableModel) tabla.getModel();
                Object obj[]
                        =
                        {
                            d.getCve(), d.getNom(), d.getPrimerAp(), d.getSegundoAp(), CtrlInterfaz.char_StringCC((d).getSexo(), "Hombre", "Mujer", 'M'),
                            CtrlInterfaz.bolean_String(d.isAlergias()), CtrlInterfaz.bolean_String(d.isDesnutricion()),
                            CtrlInterfaz.bolean_String(d.isDiabetes()), CtrlInterfaz.bolean_String(d.isObesidad()),
                            CtrlInterfaz.bolean_String(d.isSobrepeso()), d.getOtras(), nConsultas, CtrlInterfaz.char_StringCC(((Personal) d).getEstatus(), "Base", "Temporal", 'b')
                        };
                modelo.addRow(obj);
            }
        }

//        modelo.setValueAt(d.getCve(), i, 0);
//        modelo.setValueAt(d.getNom(), i, 1);
//        modelo.setValueAt(d.getPrimerAp(), i, 2);
//        modelo.setValueAt(d.getSegundoAp(), i, 3);
    }

    public static void muestraTodo(JTable tabla)
    {
        ((DefaultTableModel) tabla.getModel()).setRowCount(0);
        for (int i = 0; i < Principal.personas.length; i++)
        {
            muestra(tabla, Principal.personas[i], i, Principal.tipo);
        }
    }

    public static int[] ordenarM(HistorialClinico[][] matriz)
    {
        int filas = matriz.length;
        int[] guardaPos = new int[filas];
        for (int i = 0; i < filas; i++)
        {
            guardaPos[i] = i;
        }
        guardaPos = burbuja(guardaPos, matriz);
        return guardaPos;
    }

    public static int[] burbuja(int[] arr, HistorialClinico[][] hc)
    {

        int n = arr.length;
        int k, l;
        for (int i = 0; i < n - 1; i++)
        {
            for (int j = 0; j < n - i - 1; j++)
            {
                if (hc[arr[j]] != null)
                {
                    k = hc[arr[j]].length;
                } else
                {
                    k = 0;
                }
                if (hc[arr[j + 1]] != null)
                {
                    l = hc[arr[j + 1]].length;
                } else
                {
                    l = 0;
                }
                if (k < l)
                {
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
            }
        }
        return arr;
    }

    public static int[] burbuja(int[] arr)
    {
        int n = arr.length;
        int k, l;
        for (int i = 0; i < n - 1; i++)
        {
            for (int j = 0; j < n - i - 1; j++)
            {
                if (arr[j] < arr[j + 1])
                {
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
            }
        }
        return arr;
    }

    public static int[] invertirArray(int[] array)
    {
        int longitud = array.length;
        for (int i = 0; i < longitud / 2; i++)
        {
            // Intercambiar elementos desde los extremos hacia el centro
            int temp = array[i];
            array[i] = array[longitud - 1 - i];
            array[longitud - 1 - i] = temp;
        }
        return array;
    }

    public int char_int(char c, char c2)
    {
        if (c == c2)
        {
            return 1;
        } else
        {
            return 2;
        }
    }

    public void filtra()
    {
        String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";

        String sexo, viveCon, carrera, estatus, frecuencia;
        switch (cbxSexo.getSelectedIndex())
        {
            case 0:
                sexo = null;
                break;
            case 1:
                sexo = "M";
                break;
            case 2:
                sexo = "F";
                break;
            default:
                throw new AssertionError();
        }
        switch (cbxEstatus.getSelectedIndex())
        {
            case 0:
                estatus = null;
                break;
            case 1:
                estatus = "Base";
                break;
            case 2:
                estatus = "Temporal";
                break;
            default:
                throw new AssertionError();
        }
        switch (cbxFrecuencia.getSelectedIndex())
        {
            case 0:
                frecuencia = null;
                break;
            case 1:
                frecuencia = "ASC";
                break;
            case 2:
                frecuencia = "DESC";
                break;
            default:
                throw new AssertionError();
        }
        switch (cbxSexo.getSelectedIndex())
        {
            case 0:
                sexo = null;
                break;
            case 1:
                sexo = "M";
                break;
            case 2:
                sexo = "F";
                break;
            default:
                throw new AssertionError();
        }
        switch (cbxViveCon.getSelectedIndex())
        {
            case 0:
                viveCon = null;
                break;
            case 1:
                viveCon = "Papá";
                break;
            case 2:
                viveCon = "Mamá";
                break;
            case 3:
                viveCon = "Ambos";
                break;
            default:
                throw new AssertionError();
        }
        switch (cbxCarreras.getSelectedIndex())
        {//Carreras, LISW, LIP, LSC, LIPI, LIM, LIC
            case 0:
                carrera = null;
                break;
            case 1:
                carrera = "LISW";
                break;
            case 2:
                carrera = "LIP";
                break;
            case 3:
                carrera = "LSC";
                break;
            case 4:
                carrera = "LIPI";
                break;
            case 5:
                carrera = "LIM";
                break;
            case 6:
                carrera = "LIC";
                break;
            default:
                throw new AssertionError();
        }

        try (Connection conn = DriverManager.getConnection(url))
        {

            AccessDBConnection.obtenerDatosFiltrados(conn, sexo, viveCon, carrera, estatus, jcbxDesnutricion.isSelected(), jcbxSobrepeso.isSelected(), jcbxAlergias.isSelected(), jcbxObesidad.isSelected(), jcbxDiabetes.isSelected(), jcbxOtras.isSelected(), frecuencia, (Principal.tipo == 1 ? "A" : "P"), tabla);
        } catch (SQLException e)
        {
            e.printStackTrace();
        }
        if (sexo == null && viveCon == null && carrera == null && estatus == null
                && !jcbxDesnutricion.isSelected() && !jcbxSobrepeso.isSelected() && !jcbxAlergias.isSelected()
                && !jcbxObesidad.isSelected() && !jcbxDiabetes.isSelected() && !jcbxOtras.isSelected() && frecuencia == null)
        {
            CtrlInterfaz.habilitaChB(1, true, jcbxMuestraT);
        } else
        {
            CtrlInterfaz.habilitaChB(1, false, jcbxMuestraT);
        }

    }
//    Declara la instrucción que permita saber del arreglo de datos del proyecyo si son de la clase de 
//    alumnos o de la clase de personal

//    public class A extends B implements C, D {
//    // Resto de la implementación de la clase A
//}
    private void generarPDFDesdeJTable(JTable jTable)
    {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JButton Cancelar3;
    private javax.swing.JButton Cancelar4;
    private javax.swing.JTextField CveRegistro;
    private javax.swing.JTextField CveRegistro1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnBuscarC1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JToggleButton btnElimina;
    private javax.swing.JToggleButton btnElimina1;
    private javax.swing.JComboBox<String> cbxCarreras;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JComboBox<String> cbxFrecuencia;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxViveCon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JCheckBox jcbxAlergias;
    private javax.swing.JCheckBox jcbxDesnutricion;
    private javax.swing.JCheckBox jcbxDiabetes;
    private javax.swing.JCheckBox jcbxMuestraT;
    private javax.swing.JCheckBox jcbxObesidad;
    private javax.swing.JCheckBox jcbxOtras;
    private javax.swing.JCheckBox jcbxSelecTodos;
    private javax.swing.JCheckBox jcbxSobrepeso;
    private javax.swing.JLabel labelAntece;
    private javax.swing.JLabel labelAp;
    private javax.swing.JLabel labelM;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelP;
    private javax.swing.JLabel labelPT;
    private javax.swing.JLabel labelSegAp;
    private javax.swing.JList<String> listCitas;
    private javax.swing.JTabbedPane pesta;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JLabel titulaoMe;
    private javax.swing.JLabel tituloA;
    private javax.swing.JLabel tituloP;
    private javax.swing.JLabel tituloPlan;
    // End of variables declaration//GEN-END:variables
}
