package poo;

import BD.AccessDBConnection;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.metal.MetalLookAndFeel;
import pack1.Controlador;
import pack1.HistorialClinico;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class HistClinico extends javax.swing.JFrame
{

    Object[] obj;
    /**
     * Creates new form HistClinico
     */
    public HistClinico(Object[] obj)
    {
        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.obj = obj;
        initComponents();
    }
    public HistClinico()
    {
        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        apellidoPs = new javax.swing.JLabel();
        nombreP = new javax.swing.JLabel();
        apellidoP = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtPadecim = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxAntece = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtMedic = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPlan = new javax.swing.JTextArea();
        label4 = new java.awt.Label();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONSULTA MÉDICA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        apellidoPs.setBackground(new java.awt.Color(255, 255, 255));
        apellidoPs.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        apellidoPs.setForeground(new java.awt.Color(255, 255, 255));
        apellidoPs.setText("ApelllidoM");
        jPanel1.add(apellidoPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 200, -1));

        nombreP.setBackground(new java.awt.Color(255, 255, 255));
        nombreP.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        nombreP.setForeground(new java.awt.Color(255, 255, 255));
        nombreP.setText("Nombre");
        jPanel1.add(nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        apellidoP.setBackground(new java.awt.Color(255, 255, 255));
        apellidoP.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        apellidoP.setForeground(new java.awt.Color(255, 255, 255));
        apellidoP.setText("ApelllidoP");
        jPanel1.add(apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, -1));

        jtxtPadecim.setBackground(new java.awt.Color(204, 204, 204));
        jtxtPadecim.setColumns(20);
        jtxtPadecim.setLineWrap(true);
        jtxtPadecim.setRows(5);
        jtxtPadecim.setWrapStyleWord(true);
        jtxtPadecim.setAutoscrolls(false);
        jtxtPadecim.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtxtPadecimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtxtPadecimFocusLost(evt);
            }
        });
        jtxtPadecim.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jtxtPadecimMouseEntered(evt);
            }
        });
        jtxtPadecim.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtxtPadecimKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtxtPadecimKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(jtxtPadecim);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 110));

        jtxAntece.setBackground(new java.awt.Color(204, 204, 204));
        jtxAntece.setColumns(20);
        jtxAntece.setLineWrap(true);
        jtxAntece.setRows(5);
        jtxAntece.setWrapStyleWord(true);
        jtxAntece.setAutoscrolls(false);
        jtxAntece.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtxAnteceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtxAnteceFocusLost(evt);
            }
        });
        jtxAntece.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtxAnteceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtxAnteceKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtxAntece);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 280, 110));

        jtxtMedic.setBackground(new java.awt.Color(204, 204, 204));
        jtxtMedic.setColumns(20);
        jtxtMedic.setLineWrap(true);
        jtxtMedic.setRows(5);
        jtxtMedic.setWrapStyleWord(true);
        jtxtMedic.setAutoscrolls(false);
        jtxtMedic.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtxtMedicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtxtMedicFocusLost(evt);
            }
        });
        jtxtMedic.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtxtMedicKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtxtMedicKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtxtMedic);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 110));

        jtxtPlan.setBackground(new java.awt.Color(204, 204, 204));
        jtxtPlan.setColumns(20);
        jtxtPlan.setLineWrap(true);
        jtxtPlan.setRows(5);
        jtxtPlan.setWrapStyleWord(true);
        jtxtPlan.setAutoscrolls(false);
        jtxtPlan.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jtxtPlanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtxtPlanFocusLost(evt);
            }
        });
        jtxtPlan.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtxtPlanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtxtPlanKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtPlan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 270, 110));

        label4.setBackground(new java.awt.Color(0, 0, 51));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Plan de tratamiento");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        label3.setBackground(new java.awt.Color(0, 0, 51));
        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Medicamento");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        label2.setBackground(new java.awt.Color(0, 0, 51));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Antecedentes previos");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        label5.setBackground(new java.awt.Color(0, 0, 51));
        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Padecimiento actual.");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GuardarActionPerformed
    {//GEN-HEADEREND:event_GuardarActionPerformed
        // TODO add your handling code here:

        if (Validaciones.validaLongitud(2, this, "Debe llenar todos los campos",
                jtxtPlan, jtxtMedic, jtxAntece, jtxtPadecim) == false)
        {
            Date hoy = new Date();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm", new Locale("es", "ES"));
            // Formatea la fecha en español
            String fechaFormateada = formatoFecha.format(hoy);
            String url = "jdbc:ucanaccess://BD\\Proyecto2P.accdb";

            try (Connection conn = DriverManager.getConnection(url))
            {
                Object[] persona = {
                  obj[0], jtxtPadecim.getText(), jtxAntece.getText(),
                    jtxtMedic.getText(), jtxtPlan.getText()
                };
                System.out.println("Insercion de cita");
                AccessDBConnection.insertarDatosHistorial(conn, persona);
                dispose();

            } catch (SQLException e)
            {
                e.printStackTrace();
            }
            
            
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void jtxtMedicKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtMedicKeyTyped
    {//GEN-HEADEREND:event_jtxtMedicKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfanumerico(evt, 100, jtxtMedic.getText());

    }//GEN-LAST:event_jtxtMedicKeyTyped

    private void jtxAnteceKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxAnteceKeyTyped
    {//GEN-HEADEREND:event_jtxAnteceKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfabeticos(evt, 100, jtxAntece.getText());

    }//GEN-LAST:event_jtxAnteceKeyTyped

    private void jtxtPadecimKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtPadecimKeyTyped
    {//GEN-HEADEREND:event_jtxtPadecimKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfanumerico(evt, 100, jtxtPadecim.getText());

    }//GEN-LAST:event_jtxtPadecimKeyTyped

    private void jtxtPlanKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtPlanKeyTyped
    {//GEN-HEADEREND:event_jtxtPlanKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfanumerico(evt, 100, jtxtPlan.getText());
    }//GEN-LAST:event_jtxtPlanKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        nombreP.setText((String)obj[1]);
        apellidoP.setText((String)obj[2]);
        apellidoPs.setText((String)obj[3]);
    }//GEN-LAST:event_formWindowOpened

    private void jtxtPadecimKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtPadecimKeyPressed
    {//GEN-HEADEREND:event_jtxtPadecimKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, jtxAntece);
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPadecimKeyPressed

    private void jtxtMedicKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtMedicKeyPressed
    {//GEN-HEADEREND:event_jtxtMedicKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, jtxtPlan);
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtMedicKeyPressed

    private void jtxAnteceKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxAnteceKeyPressed
    {//GEN-HEADEREND:event_jtxAnteceKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, jtxtMedic);
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxAnteceKeyPressed

    private void jtxtPlanKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtxtPlanKeyPressed
    {//GEN-HEADEREND:event_jtxtPlanKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPlanKeyPressed

    private void jtxtPadecimMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jtxtPadecimMouseEntered
    {//GEN-HEADEREND:event_jtxtPadecimMouseEntered
        
      

       
    }//GEN-LAST:event_jtxtPadecimMouseEntered

    private void jtxtPadecimFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtPadecimFocusGained
    {//GEN-HEADEREND:event_jtxtPadecimFocusGained
        // TODO add your handling code here:
        jtxtPadecim.setBackground(Color.white);

    }//GEN-LAST:event_jtxtPadecimFocusGained

    private void jtxtPadecimFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtPadecimFocusLost
    {//GEN-HEADEREND:event_jtxtPadecimFocusLost
        // TODO add your handling code here:
        jtxtPadecim.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jtxtPadecimFocusLost

    private void jtxAnteceFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxAnteceFocusGained
    {//GEN-HEADEREND:event_jtxAnteceFocusGained
        // TODO add your handling code here:
        jtxAntece.setBackground(Color.white);
    }//GEN-LAST:event_jtxAnteceFocusGained

    private void jtxtMedicFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtMedicFocusGained
    {//GEN-HEADEREND:event_jtxtMedicFocusGained
        // TODO add your handling code here:
        jtxtMedic.setBackground(Color.white);
    }//GEN-LAST:event_jtxtMedicFocusGained

    private void jtxtPlanFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtPlanFocusGained
    {//GEN-HEADEREND:event_jtxtPlanFocusGained
        // TODO add your handling code here:
        jtxtPlan.setBackground(Color.white);
    }//GEN-LAST:event_jtxtPlanFocusGained

    private void jtxAnteceFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxAnteceFocusLost
    {//GEN-HEADEREND:event_jtxAnteceFocusLost
        // TODO add your handling code here:
        jtxAntece.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jtxAnteceFocusLost

    private void jtxtMedicFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtMedicFocusLost
    {//GEN-HEADEREND:event_jtxtMedicFocusLost
        // TODO add your handling code here:
        jtxtMedic.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jtxtMedicFocusLost

    private void jtxtPlanFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtxtPlanFocusLost
    {//GEN-HEADEREND:event_jtxtPlanFocusLost
        // TODO add your handling code here:
        jtxtPlan.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jtxtPlanFocusLost

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HistClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HistClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HistClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HistClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new HistClinico().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel apellidoP;
    private javax.swing.JLabel apellidoPs;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jtxAntece;
    private javax.swing.JTextArea jtxtMedic;
    private javax.swing.JTextArea jtxtPadecim;
    private javax.swing.JTextArea jtxtPlan;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JLabel nombreP;
    // End of variables declaration//GEN-END:variables
}
