package poo;

import BD.AccessDBConnection;
import cjb.ci.Mensajes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import pack1.Alumnos;
import pack1.Controlador;
import pack1.Personal;
import static poo.Modifica.aler;
import static poo.Modifica.des;
import static poo.Modifica.diab;
import static poo.Modifica.obec;
import static poo.Modifica.sob;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class ModificaP extends javax.swing.JFrame
{

    /**
     * Creates new form Registro
     */
    static char c;
    static int vc;
    static int ca;
    static boolean des = false;
    static boolean sob = false;
    static boolean aler = false;
    static boolean diab = false;
    static boolean obec = false;
    static String otr = "";
    Object[] obj;

    public ModificaP()
    {
        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }
    
    public ModificaP(Object[] obj)
    {
        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.obj = obj;
        initComponents();
        jTNombre.setText((String)obj[1]);
        jTPA.setText((String)obj[2]);
        jTSA.setText((String)obj[3]);
        nombreP.setText((String)obj[1]);
        apellidoP.setText((String)obj[2]);
        apellidoPs.setText((String)obj[3]);
        des = (boolean)obj[5];
        sob = (boolean)obj[6];
        aler = (boolean)obj[7];
        obec = (boolean)obj[8];
        diab = (boolean)obj[9];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        siguineteRA = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        checkOtras = new javax.swing.JCheckBox();
        chekDesnut = new javax.swing.JCheckBox();
        checkSobre = new javax.swing.JCheckBox();
        checkAler = new javax.swing.JCheckBox();
        checkObes = new javax.swing.JCheckBox();
        checkDiab = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxtaOtras = new javax.swing.JTextArea();
        cbxEstatus = new javax.swing.JComboBox<>();
        Estatus = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        nombreP = new javax.swing.JLabel();
        apellidoP = new javax.swing.JLabel();
        apellidoPs = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTSA = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTPA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguineteRA.setText("Finalizar");
        siguineteRA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                siguineteRAActionPerformed(evt);
            }
        });
        jPanel1.add(siguineteRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        checkOtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkOtras.setForeground(new java.awt.Color(255, 255, 255));
        checkOtras.setText("Otras");
        checkOtras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkOtrasActionPerformed(evt);
            }
        });
        jPanel1.add(checkOtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));

        chekDesnut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chekDesnut.setForeground(new java.awt.Color(255, 255, 255));
        chekDesnut.setText("Desnutrición");
        chekDesnut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chekDesnutActionPerformed(evt);
            }
        });
        jPanel1.add(chekDesnut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        checkSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkSobre.setForeground(new java.awt.Color(255, 255, 255));
        checkSobre.setText("Sobrepeso");
        checkSobre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkSobreActionPerformed(evt);
            }
        });
        jPanel1.add(checkSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        checkAler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkAler.setForeground(new java.awt.Color(255, 255, 255));
        checkAler.setText("Alergias");
        checkAler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkAlerActionPerformed(evt);
            }
        });
        jPanel1.add(checkAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        checkObes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkObes.setForeground(new java.awt.Color(255, 255, 255));
        checkObes.setText("Obesidad");
        checkObes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkObesActionPerformed(evt);
            }
        });
        jPanel1.add(checkObes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 20));

        checkDiab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkDiab.setForeground(new java.awt.Color(255, 255, 255));
        checkDiab.setText("Diabetes");
        checkDiab.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkDiabActionPerformed(evt);
            }
        });
        jPanel1.add(checkDiab, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, 20));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICA PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jxtaOtras.setColumns(20);
        jxtaOtras.setLineWrap(true);
        jxtaOtras.setRows(5);
        jxtaOtras.setWrapStyleWord(true);
        jxtaOtras.setAutoscrolls(false);
        jxtaOtras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jxtaOtrasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jxtaOtras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 190, 100));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base", "Temporal" }));
        cbxEstatus.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxEstatusItemStateChanged(evt);
            }
        });
        cbxEstatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxEstatusActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        Estatus.setForeground(java.awt.Color.white);
        Estatus.setText("Estatus");
        jPanel1.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreP.setForeground(new java.awt.Color(255, 255, 255));
        nombreP.setText("Nombre");
        jPanel2.add(nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        apellidoP.setForeground(new java.awt.Color(255, 255, 255));
        apellidoP.setText("ApelllidoP");
        jPanel2.add(apellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        apellidoPs.setForeground(new java.awt.Color(255, 255, 255));
        apellidoPs.setText("ApelllidoM");
        jPanel2.add(apellidoPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 590, 50));

        Admin.setText("Modo Admin");
        Admin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTSA.setText("Segundo Apellido");
        jTSA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTSAActionPerformed(evt);
            }
        });
        jPanel3.add(jTSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 170, -1));

        jTNombre.setText("Nombre");
        jPanel3.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jTPA.setText("Primer Apellido");
        jPanel3.add(jTPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 590, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siguineteRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguineteRAActionPerformed

        if (checkOtras.isSelected() == true && jxtaOtras.getText().length() < 2)
        {
            Mensajes.error(this, "Debe especificar <otras>");

        } else
        {
            if (jPanel3.isVisible())
            {
                obj[1] = (jTNombre.getText());
                obj[2] = (jTPA.getText());
                obj[3] = (jTSA.getText());
            }
            Object[] persona =
            {
                obj[0], obj[1], obj[2], obj[3], des, sob, aler, obec,
                diab, jxtaOtras.getText(), cbxEstatus.getSelectedItem()
            };
            try
            {
                AccessDBConnection.modificarD(obj[0].toString(), this, "P", persona);

            } catch (SQLException e)
            {
                System.out.println("A");
            }
            this.dispose();

        }

    }//GEN-LAST:event_siguineteRAActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void checkOtrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkOtrasActionPerformed
    {//GEN-HEADEREND:event_checkOtrasActionPerformed
        // TODO add your handling code here:

        jxtaOtras.setVisible(checkOtras.isSelected());
        if (checkOtras.isSelected() == false)
        {
            otr = "";
        }

    }//GEN-LAST:event_checkOtrasActionPerformed

    private void chekDesnutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chekDesnutActionPerformed
    {//GEN-HEADEREND:event_chekDesnutActionPerformed
        // TODO add your handling code here:
        if (chekDesnut.isSelected())
        {
            des = true;
        } else
        {
            des = false;
        }
    }//GEN-LAST:event_chekDesnutActionPerformed

    private void checkSobreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkSobreActionPerformed
    {//GEN-HEADEREND:event_checkSobreActionPerformed
        // TODO add your handling code here:
        if (checkSobre.isSelected())
        {
            sob = true;
        } else
        {
            sob = false;
        }
    }//GEN-LAST:event_checkSobreActionPerformed

    private void checkAlerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkAlerActionPerformed
    {//GEN-HEADEREND:event_checkAlerActionPerformed
        // TODO add your handling code here:
        if (checkAler.isSelected())
        {
            aler = true;
        } else
        {
            aler = false;
        }
    }//GEN-LAST:event_checkAlerActionPerformed

    private void checkObesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkObesActionPerformed
    {//GEN-HEADEREND:event_checkObesActionPerformed
        // TODO add your handling code here:
        if (checkObes.isSelected())
        {
            obec = true;
        } else
        {
            obec = false;
        }
    }//GEN-LAST:event_checkObesActionPerformed

    private void checkDiabActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkDiabActionPerformed
    {//GEN-HEADEREND:event_checkDiabActionPerformed
        // TODO add your handling code here:
        if (checkDiab.isSelected())
        {
            diab = true;
        } else
        {
            diab = false;
        }
    }//GEN-LAST:event_checkDiabActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:

        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        cbxEstatusItemStateChanged(null);
        
        checkAler.setSelected(aler);
        checkDiab.setSelected(diab);
        checkObes.setSelected(obec);
        checkSobre.setSelected(sob);
        chekDesnut.setSelected(des);
        if (((String)obj[11]).equals("Base"))
        {
            cbxEstatus.setSelectedIndex(0);
        }else
        {
            cbxEstatus.setSelectedIndex(1);
        }
        if (!((String)obj[10]).isEmpty())
        {
            checkOtras.setSelected(true);
            jxtaOtras.setText((String)obj[10]);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cbxEstatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxEstatusActionPerformed
    {//GEN-HEADEREND:event_cbxEstatusActionPerformed
        // TODO add your handling code here:
        if (cbxEstatus.getSelectedItem().equals("Base"))
        {
            c = 'b';
        } else
        {
            c = 't';
        }
    }//GEN-LAST:event_cbxEstatusActionPerformed

    private void cbxEstatusItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxEstatusItemStateChanged
    {//GEN-HEADEREND:event_cbxEstatusItemStateChanged
        // TODO add your handling code here:
        if (cbxEstatus.getSelectedItem().equals("Base"))
        {
            c = 'b';
        } else
        {
            c = 't';
        }
    }//GEN-LAST:event_cbxEstatusItemStateChanged

    private void jTSAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTSAActionPerformed
    {//GEN-HEADEREND:event_jTSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSAActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AdminActionPerformed
    {//GEN-HEADEREND:event_AdminActionPerformed
        // TODO add your handling code here:
        if (jPanel3.isVisible() == false)
        {
            String pass = JOptionPane.showInputDialog("Ingrese la clave");
            if (pass.equals("1234"))
            {
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                Admin.setText("Cancelar");
            } else
            {
                Mensajes.error(this, "Error");
            }
        } else
        {
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
            Admin.setText("Modo Admin");
        }
    }//GEN-LAST:event_AdminActionPerformed

    private void jxtaOtrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jxtaOtrasKeyPressed
    {//GEN-HEADEREND:event_jxtaOtrasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jxtaOtrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Cancelar;
    private java.awt.Label Estatus;
    private javax.swing.JLabel apellidoP;
    private javax.swing.JLabel apellidoPs;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JCheckBox checkAler;
    private javax.swing.JCheckBox checkDiab;
    private javax.swing.JCheckBox checkObes;
    private javax.swing.JCheckBox checkOtras;
    private javax.swing.JCheckBox checkSobre;
    private javax.swing.JCheckBox chekDesnut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPA;
    private javax.swing.JTextField jTSA;
    private javax.swing.JTextArea jxtaOtras;
    private javax.swing.JLabel nombreP;
    private javax.swing.JButton siguineteRA;
    // End of variables declaration//GEN-END:variables

    private void SetFocused(boolean b)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
