package poo;

import java.sql.Connection;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import pack1.Alumnos;
import pack1.Controlador;
import pack1.Datos;
import pack1.HistorialClinico;
import pack1.Personal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Hansel
/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame
{

    public static int tipo = 0;
    public static Datos personas[] = null;
    public static HistorialClinico consultas[][] = null;
    public static String bCve = "";

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnNc1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnNc = new javax.swing.JButton();
        checkAlum = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        checkPer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnNc1.setText("Nueva Cita Medica");
        btnNc1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNc1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setText("Registro");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistroActionPerformed(evt);
            }
        });
        btnRegistro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnRegistroKeyPressed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, 40));

        btnNc.setText("Cita medica");
        btnNc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNcActionPerformed(evt);
            }
        });
        jPanel1.add(btnNc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 170, 60));

        checkAlum.setForeground(new java.awt.Color(255, 255, 255));
        checkAlum.setText("Alumno");
        checkAlum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkAlumActionPerformed(evt);
            }
        });
        jPanel1.add(checkAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/perosnal.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, 100));

        checkPer.setForeground(new java.awt.Color(255, 255, 255));
        checkPer.setText("Personal");
        checkPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkPerActionPerformed(evt);
            }
        });
        jPanel1.add(checkPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/almunaa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 120, 40));

        btnConsulta.setText(" Consulta ");
        btnConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 60));

        btnModif.setText("Modificaciones");
        btnModif.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, 60));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNcActionPerformed
        try
        {
            do
            {
                if (tipo == 1)
                {
                    bCve = JOptionPane.showInputDialog("Clave del alumno: ");

                } else
                {
                    bCve = JOptionPane.showInputDialog("Clave del personal: ");
                }
                if (bCve == null)
                {
                    break;
                } else
                {
                    if (bCve.trim().isEmpty())
                    {
                        JOptionPane.showMessageDialog(null, "No se ingreso ninguna clave", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        continue;
                    }
                }
                Object[] np = Controlador.ObtenerNC(bCve, this);
                if (np != null)
                {
                    HistClinico m = new HistClinico(np);
                    m.setVisible(true);
                    break;
                }
            } while (true);
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Entrada no valida, Ingrese una matricula", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnNcActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        if (personas != null)
        {
            Mensajes.error(this, "Aun no hay datos registrados");

        } else
        {
            Consultas newFrame = new Consultas();
            newFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void checkAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlumActionPerformed
        tipo = 1;

        CtrlInterfaz.habilita(checkAlum.isSelected() || checkPer.isSelected(), btnRegistro, btnConsulta, btnNc, btnModif);

        checkPer.setSelected(false);

    }//GEN-LAST:event_checkAlumActionPerformed

    private void checkPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerActionPerformed
        tipo = 2;
        CtrlInterfaz.habilita(checkAlum.isSelected() || checkPer.isSelected(), btnRegistro, btnConsulta, btnNc, btnModif);
        checkAlum.setSelected(false);
    }//GEN-LAST:event_checkPerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        if (tipo == 1)
        {
            checkAlum.setSelected(true);

        } else
        {
            if (tipo == 2)
            {
                checkPer.setSelected(true);
            } else
            {
                CtrlInterfaz.habilita(false, btnRegistro, btnConsulta, btnNc, btnModif);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModifActionPerformed
    {//GEN-HEADEREND:event_btnModifActionPerformed
        try
        {
            do
            {
                if (tipo == 1)
                {
                    bCve = JOptionPane.showInputDialog("Clave del alumno: ");

                } else
                {
                    bCve = JOptionPane.showInputDialog("Clave del personal: ");
                }
                if (bCve == null)
                {
                    break;
                } else
                {
                    if (bCve.trim().isEmpty())
                    {
                        JOptionPane.showMessageDialog(null, "No se ingreso ninguna clave", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        continue;
                    }
                }
                Object[] np = Controlador.ObtenerTD(bCve, this);
                if (np != null)
                {
                    if (tipo == 1)
                    {
                        Modifica m = new Modifica(np);
                        m.setVisible(true);
                    } else
                    {
                        ModificaP m = new ModificaP(np);
                        m.setVisible(true);
                    }

                    break;
                }
            } while (true);
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Entrada no valida, Ingrese una matricula", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnModifActionPerformed

    private void btnNc1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNc1ActionPerformed
    {//GEN-HEADEREND:event_btnNc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNc1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnRegistroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnRegistroKeyPressed
    {//GEN-HEADEREND:event_btnRegistroKeyPressed

    }//GEN-LAST:event_btnRegistroKeyPressed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistroActionPerformed
    {//GEN-HEADEREND:event_btnRegistroActionPerformed

        switch (tipo)
        {

            case 1:
                Registro val = new Registro();
                val.setVisible(true);

                break;
            case 2:
                RegistrosPer val2 = new RegistrosPer();
                val2.setVisible(true);

        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnNc;
    private javax.swing.JButton btnNc1;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton checkAlum;
    private javax.swing.JRadioButton checkPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void SetFocused(boolean b)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
