package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import pack1.Controlador;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class RegistrosPer extends javax.swing.JFrame
{

    static String nP, pAP, sAP, matriP;
    /**
     * Creates new form RegistrosPer
     */
    public static char cP;
    public static String sP;

    public RegistrosPer()
    {

        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        chechMasculino = new javax.swing.JCheckBox();
        Estatus = new java.awt.Label();
        checkFemeR = new javax.swing.JCheckBox();
        cbxEstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CveRegistro = new javax.swing.JTextField();
        NomReg = new javax.swing.JTextField();
        apellidoReg = new javax.swing.JTextField();
        segApReg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(756, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setForeground(java.awt.Color.white);
        label1.setText("Nombre");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        label2.setForeground(java.awt.Color.white);
        label2.setText("cve");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        label3.setForeground(java.awt.Color.white);
        label3.setText("Primer Apellido");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        label4.setForeground(java.awt.Color.white);
        label4.setText("Segundo Apellido");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        label5.setForeground(java.awt.Color.white);
        label5.setText("Sexo:");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        chechMasculino.setBackground(new java.awt.Color(0, 0, 51));
        chechMasculino.setForeground(new java.awt.Color(255, 255, 255));
        chechMasculino.setText("Masculino");
        chechMasculino.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chechMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(chechMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        Estatus.setForeground(java.awt.Color.white);
        Estatus.setText("Estatus");
        jPanel1.add(Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        checkFemeR.setBackground(new java.awt.Color(0, 0, 51));
        checkFemeR.setForeground(new java.awt.Color(255, 255, 255));
        checkFemeR.setText("Femenino");
        checkFemeR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkFemeRActionPerformed(evt);
            }
        });
        jPanel1.add(checkFemeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Base", "Temporal" }));
        cbxEstatus.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cbxEstatusItemStateChanged(evt);
            }
        });
        cbxEstatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxEstatusActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        CveRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CveRegistroActionPerformed(evt);
            }
        });
        CveRegistro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                CveRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CveRegistroKeyTyped(evt);
            }
        });
        jPanel1.add(CveRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 190, -1));

        NomReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NomRegActionPerformed(evt);
            }
        });
        NomReg.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                NomRegKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NomRegKeyTyped(evt);
            }
        });
        jPanel1.add(NomReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, -1));

        apellidoReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                apellidoRegActionPerformed(evt);
            }
        });
        apellidoReg.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apellidoRegKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apellidoRegKeyTyped(evt);
            }
        });
        jPanel1.add(apellidoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, -1));

        segApReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                segApRegActionPerformed(evt);
            }
        });
        segApReg.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                segApRegKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                segApRegKeyTyped(evt);
            }
        });
        jPanel1.add(segApReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        if (cbxEstatus.getSelectedItem().toString().equals("--") || (chechMasculino.isSelected() == false && checkFemeR.isSelected() == false) || CveRegistro.getText().length() == 0 || segApReg.getText().length() == 0 || apellidoReg.getText().length() == 0 || segApReg.getText().length() == 0)
        {
            Mensajes.error(this, "Debe llenar todos los campos");

        } else
        {
            nP = Controlador.capitalizarPrimerasLetras(NomReg.getText());
            pAP = Controlador.capitalizarPrimerasLetras(apellidoReg.getText());
            sAP = Controlador.capitalizarPrimerasLetras(segApReg.getText());
            matriP = CveRegistro.getText();
            RegistroPadec re = new RegistroPadec();
            re.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void cbxEstatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxEstatusActionPerformed
    {//GEN-HEADEREND:event_cbxEstatusActionPerformed
        // TODO add your handling code here:
        if (cbxEstatus.getSelectedItem().equals("Base"))
        {
            cP = 'b';
        } else
        {
            cP = 't';
        }
    }//GEN-LAST:event_cbxEstatusActionPerformed

    private void checkFemeRActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkFemeRActionPerformed
    {//GEN-HEADEREND:event_checkFemeRActionPerformed
        // TODO add your handling code here:

        chechMasculino.setSelected(false);
        sP = "F";
    }//GEN-LAST:event_checkFemeRActionPerformed

    private void chechMasculinoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chechMasculinoActionPerformed
    {//GEN-HEADEREND:event_chechMasculinoActionPerformed
        // TODO add your handling code here:

        checkFemeR.setSelected(false);
        sP = "M";
    }//GEN-LAST:event_chechMasculinoActionPerformed

    private void CveRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CveRegistroActionPerformed
    {//GEN-HEADEREND:event_CveRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CveRegistroActionPerformed

    private void CveRegistroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistroKeyPressed
    {//GEN-HEADEREND:event_CveRegistroKeyPressed
        // TODO add your handling code here:
        Validaciones.validaCopyPaste(evt, this, CveRegistro);
        Validaciones.enter(this, evt, NomReg);

        if (evt.getKeyChar() == '\n' && CveRegistro.getText() != null)
        {
            CtrlInterfaz.cambia(CveRegistro);

        }
    }//GEN-LAST:event_CveRegistroKeyPressed

    private void CveRegistroKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CveRegistroKeyTyped
    {//GEN-HEADEREND:event_CveRegistroKeyTyped
        // TODO add your handling code here:
        Validaciones.validaEntero(evt, 7, CveRegistro.getText());
    }//GEN-LAST:event_CveRegistroKeyTyped

    private void NomRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NomRegActionPerformed
    {//GEN-HEADEREND:event_NomRegActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NomRegActionPerformed

    private void NomRegKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NomRegKeyPressed
    {//GEN-HEADEREND:event_NomRegKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, apellidoReg);
    }//GEN-LAST:event_NomRegKeyPressed

    private void NomRegKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NomRegKeyTyped
    {//GEN-HEADEREND:event_NomRegKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfabeticos(evt, 20, NomReg.getText());
    }//GEN-LAST:event_NomRegKeyTyped

    private void apellidoRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_apellidoRegActionPerformed
    {//GEN-HEADEREND:event_apellidoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoRegActionPerformed

    private void apellidoRegKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoRegKeyPressed
    {//GEN-HEADEREND:event_apellidoRegKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, segApReg);
    }//GEN-LAST:event_apellidoRegKeyPressed

    private void apellidoRegKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoRegKeyTyped
    {//GEN-HEADEREND:event_apellidoRegKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfabeticos(evt, 20, apellidoReg.getText());
    }//GEN-LAST:event_apellidoRegKeyTyped

    private void segApRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_segApRegActionPerformed
    {//GEN-HEADEREND:event_segApRegActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_segApRegActionPerformed

    private void segApRegKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segApRegKeyPressed
    {//GEN-HEADEREND:event_segApRegKeyPressed
        // TODO add your handling code here:
        Validaciones.enter(this, evt, CveRegistro);
    }//GEN-LAST:event_segApRegKeyPressed

    private void segApRegKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_segApRegKeyTyped
    {//GEN-HEADEREND:event_segApRegKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfabeticos(evt, 20, segApReg.getText());
    }//GEN-LAST:event_segApRegKeyTyped

    private void cbxEstatusItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cbxEstatusItemStateChanged
    {//GEN-HEADEREND:event_cbxEstatusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstatusItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegistrosPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegistrosPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegistrosPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegistrosPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegistrosPer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField CveRegistro;
    private java.awt.Label Estatus;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField NomReg;
    private javax.swing.JTextField apellidoReg;
    private javax.swing.JComboBox<String> cbxEstatus;
    private javax.swing.JCheckBox chechMasculino;
    private javax.swing.JCheckBox checkFemeR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextField segApReg;
    // End of variables declaration//GEN-END:variables
}
