package poo;

import BD.AccessDBConnection;
import cjb.ci.Mensajes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import pack1.Alumnos;
import pack1.Controlador;
import pack1.Personal;
import static poo.Registro.c;
import static poo.Registro.ca;
import static poo.Registro.matri;
import static poo.Registro.n;
import static poo.Registro.pA;
import static poo.Registro.sA;
import static poo.Registro.vc;
import static poo.RegistrosPer.cP;
import static poo.RegistrosPer.matriP;
import static poo.RegistrosPer.nP;
import static poo.RegistrosPer.pAP;
import static poo.RegistrosPer.sP;
import static poo.RegistrosPer.sAP;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class RegistroPadec extends javax.swing.JFrame
{

    /**
     * Creates new form Registro
     */
    static boolean des = false;
    static boolean sob = false;
    static boolean aler = false;
    static boolean diab = false;
    static boolean obec = false;
    static String otr = "";

    public RegistroPadec()
    {

        try
        {
            // Crear un JScrollPane y configurar las barras de desplazamient
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        siguineteRA = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        checkOtras = new javax.swing.JCheckBox();
        chekDesnut = new javax.swing.JCheckBox();
        checkSobre = new javax.swing.JCheckBox();
        checkAler = new javax.swing.JCheckBox();
        checkObes = new javax.swing.JCheckBox();
        checkDiab = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jxtaOtras = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siguineteRA.setText("Finalizar");
        siguineteRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguineteRAActionPerformed(evt);
            }
        });
        jPanel1.add(siguineteRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        checkOtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkOtras.setForeground(new java.awt.Color(255, 255, 255));
        checkOtras.setText("Otras");
        checkOtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOtrasActionPerformed(evt);
            }
        });
        jPanel1.add(checkOtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, 20));

        chekDesnut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chekDesnut.setForeground(new java.awt.Color(255, 255, 255));
        chekDesnut.setText("Desnutrición");
        chekDesnut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekDesnutActionPerformed(evt);
            }
        });
        jPanel1.add(chekDesnut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 20));

        checkSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkSobre.setForeground(new java.awt.Color(255, 255, 255));
        checkSobre.setText("Sobrepeso");
        checkSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSobreActionPerformed(evt);
            }
        });
        jPanel1.add(checkSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 20));

        checkAler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkAler.setForeground(new java.awt.Color(255, 255, 255));
        checkAler.setText("Alergias");
        checkAler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAlerActionPerformed(evt);
            }
        });
        jPanel1.add(checkAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, 20));

        checkObes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkObes.setForeground(new java.awt.Color(255, 255, 255));
        checkObes.setText("Obesidad");
        checkObes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkObesActionPerformed(evt);
            }
        });
        jPanel1.add(checkObes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 20));

        checkDiab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkDiab.setForeground(new java.awt.Color(255, 255, 255));
        checkDiab.setText("Diabetes");
        checkDiab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDiabActionPerformed(evt);
            }
        });
        jPanel1.add(checkDiab, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 20));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PADECIMIENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jxtaOtras.setColumns(20);
        jxtaOtras.setLineWrap(true);
        jxtaOtras.setRows(5);
        jxtaOtras.setWrapStyleWord(true);
        jxtaOtras.setAutoscrolls(false);
        jxtaOtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jxtaOtrasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jxtaOtras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 290, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siguineteRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguineteRAActionPerformed

        if (checkOtras.isSelected() == true && jxtaOtras.getText().length() < 2)
        {

            Mensajes.error(this, "Debe especificar <otras>");
        } else
        {
            otr = jxtaOtras.getText();
            if (Principal.tipo == 1)
            {
                Object[] P =
                {
                    Integer.parseInt(matri), n, pA, sA, c, des, sob, aler, obec, diab, otr, "A", (vc == 1 ? "Papá" : (vc == 2 ? "Mamá" : "Ambos")),
                    (ca == 1 ? "LISW" : (ca == 2 ? "LIP" : (ca == 3 ? "LSC" : (ca == 4 ? "LIPI" : (ca == 5 ? "LIM" : "LIC")))))
                };
                AccessDBConnection.insertarR(P, this);
                
                Mensajes.exito(this, "Registro Exitoso");

            } else
            {
                if (Principal.tipo == 2)
                {
                    Object[] P =
                    {
                        Integer.parseInt(matriP), nP, pAP, sAP, sP, des, sob, aler, obec, diab, otr, "P", (cP == 'b' ? "Base" : "Temporal"),
                    };
                    AccessDBConnection.insertarR(P, this);
                    
                    Mensajes.exito(this, "Registro Exitoso");

                } else
                {
                    Mensajes.error(this, "Tipo erroneo");
                }

            }
            dispose();
        }


    }//GEN-LAST:event_siguineteRAActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_CancelarActionPerformed

    private void checkOtrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkOtrasActionPerformed
    {//GEN-HEADEREND:event_checkOtrasActionPerformed
        // TODO add your handling code here:

        jxtaOtras.setVisible(checkOtras.isSelected());
        if (checkOtras.isSelected() == false)
        {
            otr = null;
        }

    }//GEN-LAST:event_checkOtrasActionPerformed

    private void chekDesnutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chekDesnutActionPerformed
    {//GEN-HEADEREND:event_chekDesnutActionPerformed
        // TODO add your handling code here:
        if (chekDesnut.isSelected())
        {
            des = true;
        } else
        {
            des = false;
        }
    }//GEN-LAST:event_chekDesnutActionPerformed

    private void checkSobreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkSobreActionPerformed
    {//GEN-HEADEREND:event_checkSobreActionPerformed
        // TODO add your handling code here:
        if (checkSobre.isSelected())
        {
            sob = true;
        } else
        {
            sob = false;
        }
    }//GEN-LAST:event_checkSobreActionPerformed

    private void checkAlerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkAlerActionPerformed
    {//GEN-HEADEREND:event_checkAlerActionPerformed
        // TODO add your handling code here:
        if (checkAler.isSelected())
        {
            aler = true;
        } else
        {
            aler = false;
        }
    }//GEN-LAST:event_checkAlerActionPerformed

    private void checkObesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkObesActionPerformed
    {//GEN-HEADEREND:event_checkObesActionPerformed
        // TODO add your handling code here:
        if (checkObes.isSelected())
        {
            obec = true;
        } else
        {
            obec = false;
        }
    }//GEN-LAST:event_checkObesActionPerformed

    private void checkDiabActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkDiabActionPerformed
    {//GEN-HEADEREND:event_checkDiabActionPerformed
        // TODO add your handling code here:
        if (checkDiab.isSelected())
        {
            diab = true;
        } else
        {
            diab = false;
        }
    }//GEN-LAST:event_checkDiabActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        jxtaOtras.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jxtaOtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jxtaOtrasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n')
        {
            evt.consume();
        }
    }//GEN-LAST:event_jxtaOtrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JCheckBox checkAler;
    private javax.swing.JCheckBox checkDiab;
    private javax.swing.JCheckBox checkObes;
    private javax.swing.JCheckBox checkOtras;
    private javax.swing.JCheckBox checkSobre;
    private javax.swing.JCheckBox chekDesnut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jxtaOtras;
    private javax.swing.JButton siguineteRA;
    // End of variables declaration//GEN-END:variables

    private void SetFocused(boolean b)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
