package vista;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import javax.swing.JOptionPane;
import controlador.Controlador;
import modelo.entidades.Datos;
import modelo.seguridad.SesionActual;
import servicios.GestorCierre;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Hansel
/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame
{

    public static int tipo = 0;
    public static Datos personas[] = null;
    public static String bCve = "";
    Controlador miControlador = new Controlador();

    // Variables para controlar los permisos según el rol (como los bits de chmod)
    private boolean estadoRegistro = false;
    private boolean estadoConsulta = false;
    private boolean estadoModif = false;
    private boolean estadoNc = false;
// Banderas para los futuros botones del sistema:
    private boolean estadoLogs = false;
    private boolean estadoBackup = false;

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        initComponents();

        configurarAccesosSegunRol();

        Runtime.getRuntime().addShutdownHook(new Thread(() ->
        {
            GestorCierre.generarResumen();
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnNc1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnNc = new javax.swing.JButton();
        checkAlum = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        checkPer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCopiaS = new javax.swing.JButton();

        btnNc1.setText("Nueva Cita Medica");
        btnNc1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNc1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setText("Registro");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistroActionPerformed(evt);
            }
        });
        btnRegistro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnRegistroKeyPressed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, 40));

        btnNc.setText("Cita medica");
        btnNc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNcActionPerformed(evt);
            }
        });
        jPanel1.add(btnNc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 170, 60));

        checkAlum.setForeground(new java.awt.Color(255, 255, 255));
        checkAlum.setText("Alumno");
        checkAlum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkAlumActionPerformed(evt);
            }
        });
        jPanel1.add(checkAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/perosnal.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, 100));

        checkPer.setForeground(new java.awt.Color(255, 255, 255));
        checkPer.setText("Personal");
        checkPer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkPerActionPerformed(evt);
            }
        });
        jPanel1.add(checkPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/almunaa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 120, 40));

        btnConsulta.setText(" Consulta ");
        btnConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 60));

        btnModif.setText("Modificaciones");
        btnModif.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModifActionPerformed(evt);
            }
        });
        jPanel1.add(btnModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, 60));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnCopiaS.setText("Vista Logs");
        btnCopiaS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCopiaSActionPerformed(evt);
            }
        });
        jPanel1.add(btnCopiaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNcActionPerformed

        // 1. BARRERA DE SEGURIDAD (Control de Roles mediante el Singleton)
        String rolActual = SesionActual.getInstance().getRol();
        if (!rolActual.equals("Administrador") && !rolActual.equals("Medico"))
        {
            JOptionPane.showMessageDialog(this,
                    "Acceso Denegado: Su rol actual ('" + rolActual + "') no tiene permisos para modificar expedientes.",
                    "Bloqueo de Seguridad", JOptionPane.WARNING_MESSAGE);
            return; // Cortamos la ejecución aquí, no se le pide ninguna clave
        }

        boolean seguirBuscando = true;

        // 2. CICLO DE BÚSQUEDA
        while (seguirBuscando)
        {

            String mensaje = (Principal.tipo == 1) ? "Clave del alumno:" : "Clave del personal:";
            String bCve = JOptionPane.showInputDialog(this, mensaje, "Buscar para Modificar", JOptionPane.QUESTION_MESSAGE);

            // Si el usuario presiona "Cancelar" o la 'X' de la ventana
            if (bCve == null)
            {
                break;
            }

            // Si el usuario le da "Aceptar" pero dejó el cuadro en blanco
            if (bCve.trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "No se ingresó ninguna clave.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                continue; // Regresa al inicio del while y vuelve a preguntar
            }

            // Validación preventiva: ¿Lo que escribió son puros números?
            if (!bCve.matches("\\d+"))
            {
                JOptionPane.showMessageDialog(this, "Entrada no válida. Ingrese únicamente números.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                continue; // Regresa al inicio del while
            }

            // 3. COMUNICACIÓN CON EL CONTROLADOR
            // Pasamos el string limpio y validado a nuestro objeto Controlador
            Object[] datosPersona = miControlador.obtenerTodosLosDatos(bCve, this);

            // 4. APERTURA DE INTERFAZ
            if (datosPersona != null)
            {
                // Se encontró la persona, abrimos la ventana inyectando los datos
                if (Principal.tipo == 1)
                {
                    HistClinico m = new HistClinico(datosPersona);
                    m.setVisible(true);
                } else
                {
                    HistClinico m = new HistClinico(datosPersona);
                    m.setVisible(true);
                }

                // Rompemos el ciclo porque ya cumplimos el objetivo
                seguirBuscando = false;
            }
            // Si el Controlador devuelve null (porque no encontró la clave en la BD),
            // el Controlador ya mostró su propio mensaje de "Clave no encontrada",
            // y el ciclo 'while' simplemente volverá a pedir la clave.
        }
    }//GEN-LAST:event_btnNcActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        if (personas != null)
        {
            Mensajes.error(this, "Aun no hay datos registrados");

        } else
        {
            Consultas newFrame = new Consultas();
            newFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void checkAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlumActionPerformed
        tipo = 1;
        checkPer.setSelected(false);
        actualizarBotonesPorSeleccion();

    }//GEN-LAST:event_checkAlumActionPerformed

    private void checkPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPerActionPerformed
        tipo = 2;
        checkAlum.setSelected(false);
        actualizarBotonesPorSeleccion();
    }//GEN-LAST:event_checkPerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        if (tipo == 1)
        {
            checkAlum.setSelected(true);

        } else
        {
            if (tipo == 2)
            {
                checkPer.setSelected(true);
            } else
            {
                CtrlInterfaz.habilita(false, btnRegistro, btnConsulta, btnNc, btnModif);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModifActionPerformed
    {//GEN-HEADEREND:event_btnModifActionPerformed
        // 1. BARRERA DE SEGURIDAD (Control de Roles mediante el Singleton)
        String rolActual = SesionActual.getInstance().getRol();
        if (!rolActual.equals("Administrador") && !rolActual.equals("Medico"))
        {
            JOptionPane.showMessageDialog(this,
                    "Acceso Denegado: Su rol actual ('" + rolActual + "') no tiene permisos para modificar expedientes.",
                    "Bloqueo de Seguridad", JOptionPane.WARNING_MESSAGE);
            return; // Cortamos la ejecución aquí, no se le pide ninguna clave
        }

        boolean seguirBuscando = true;

        // 2. CICLO DE BÚSQUEDA
        while (seguirBuscando)
        {

            String mensaje = (Principal.tipo == 1) ? "Clave del alumno:" : "Clave del personal:";
            String bCve = JOptionPane.showInputDialog(this, mensaje, "Buscar para Modificar", JOptionPane.QUESTION_MESSAGE);

            // Si el usuario presiona "Cancelar" o la 'X' de la ventana
            if (bCve == null)
            {
                break;
            }

            // Si el usuario le da "Aceptar" pero dejó el cuadro en blanco
            if (bCve.trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "No se ingresó ninguna clave.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                continue; // Regresa al inicio del while y vuelve a preguntar
            }

            // Validación preventiva: ¿Lo que escribió son puros números?
            if (!bCve.matches("\\d+"))
            {
                JOptionPane.showMessageDialog(this, "Entrada no válida. Ingrese únicamente números.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                continue; // Regresa al inicio del while
            }

            // 3. COMUNICACIÓN CON EL CONTROLADOR
            // Pasamos el string limpio y validado a nuestro objeto Controlador
            Object[] datosPersona = miControlador.obtenerTodosLosDatos(bCve, this);

            // 4. APERTURA DE INTERFAZ
            if (datosPersona != null)
            {
                // Se encontró la persona, abrimos la ventana inyectando los datos
                if (Principal.tipo == 1)
                {
                    Modifica m = new Modifica(datosPersona);
                    m.setVisible(true);
                } else
                {
                    ModificaP m = new ModificaP(datosPersona);
                    m.setVisible(true);
                }

                // Rompemos el ciclo porque ya cumplimos el objetivo
                seguirBuscando = false;
            }
            // Si el Controlador devuelve null (porque no encontró la clave en la BD),
            // el Controlador ya mostró su propio mensaje de "Clave no encontrada",
            // y el ciclo 'while' simplemente volverá a pedir la clave.
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnNc1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNc1ActionPerformed
    {//GEN-HEADEREND:event_btnNc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNc1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnRegistroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnRegistroKeyPressed
    {//GEN-HEADEREND:event_btnRegistroKeyPressed

    }//GEN-LAST:event_btnRegistroKeyPressed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistroActionPerformed
    {//GEN-HEADEREND:event_btnRegistroActionPerformed

        switch (tipo)
        {

            case 1:
                Registro val = new Registro();
                val.setVisible(true);

                break;
            case 2:
                RegistrosPer val2 = new RegistrosPer();
                val2.setVisible(true);

        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnCopiaSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCopiaSActionPerformed
    {//GEN-HEADEREND:event_btnCopiaSActionPerformed
        // TODO add your handling code here:
        VistaAuditoria v = new VistaAuditoria();
        v.setVisible(true);
    }//GEN-LAST:event_btnCopiaSActionPerformed

    private void actualizarBotonesPorSeleccion()
    {
        boolean seleccionado = checkAlum.isSelected() || checkPer.isSelected();

        // En lugar de mandar todos a la vez a CtrlInterfaz.habilita,
        // evaluamos cada uno contra su permiso de rol usando (seleccionado && estadoDelRol)
        // Si tu CtrlInterfaz.habilita acepta un solo componente:
        CtrlInterfaz.habilita(seleccionado && estadoRegistro, btnRegistro);
        CtrlInterfaz.habilita(seleccionado && estadoConsulta, btnConsulta);
        CtrlInterfaz.habilita(seleccionado && estadoModif, btnModif);
        CtrlInterfaz.habilita(estadoBackup, btnCopiaS);

        // Habilitar botón de Cita Médica
        btnNc.setEnabled(seleccionado && estadoNc);
    }

    private void configurarAccesosSegunRol()
    {
        switch (SesionActual.getInstance().getRol())
        {
            case "Administrador":
                // Nivel 3: Todos los permisos (rwx)
                estadoRegistro = true;
                estadoConsulta = true;
                estadoModif = true;
                estadoNc = true;
                estadoLogs = true;
                estadoBackup = true;
                break;

            case "Medico":
                // Nivel 2: Operativo Clínico (rw-)
                estadoRegistro = true;
                estadoConsulta = true;
                estadoModif = true;
                estadoNc = true;
                estadoLogs = false;   // Sin acceso al sistema
                estadoBackup = false; // Sin acceso al sistema
                break;

            case "Asistente":
                // Nivel 1: Solo captura y lectura (r--)
                estadoRegistro = true;
                estadoConsulta = true;
                estadoModif = false; // No puede alterar expedientes
                estadoNc = false;    // No da consultas médicas
                estadoLogs = false;
                estadoBackup = false;
                break;
        }

        // Los botones de sistema (Logs/Backup) no dependen de los CheckBox, 
        // así que los podemos desaparecer de la interfaz desde aquí:
        // btnLogs.setVisible(estadoLogs);
        // btnBackup.setVisible(estadoBackup);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnCopiaS;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnNc;
    private javax.swing.JButton btnNc1;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton checkAlum;
    private javax.swing.JRadioButton checkPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void SetFocused(boolean b)
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
