/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Francisco
 */
public class PagP extends javax.swing.JFrame
{

    /**
     * Creates new form PagP
     */
    public PagP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Registro = new javax.swing.JButton();
        Alumno = new javax.swing.JCheckBox();
        Personal = new javax.swing.JCheckBox();
        HClin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salida = new javax.swing.JButton();
        ConGrl = new javax.swing.JButton();
        Registro1 = new javax.swing.JButton();
        Alumno1 = new javax.swing.JCheckBox();
        Personal1 = new javax.swing.JCheckBox();
        HClin1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salida1 = new javax.swing.JButton();
        ConGrl1 = new javax.swing.JButton();
        Registro2 = new javax.swing.JButton();
        Alumno2 = new javax.swing.JCheckBox();
        Personal2 = new javax.swing.JCheckBox();
        HClin2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salida2 = new javax.swing.JButton();
        ConGrl2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Registro.setText("Registro");
        Registro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RegistroActionPerformed(evt);
            }
        });
        Registro.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                RegistroKeyPressed(evt);
            }
        });

        Alumno.setForeground(new java.awt.Color(255, 255, 255));
        Alumno.setText("Alumno");

        Personal.setForeground(new java.awt.Color(255, 255, 255));
        Personal.setText("Personal");
        Personal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PersonalActionPerformed(evt);
            }
        });

        HClin.setText("Modificaciones");
        HClin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HClinActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/perosnal.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/almunaa.png"))); // NOI18N

        salida.setText("Salir");
        salida.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salidaActionPerformed(evt);
            }
        });

        ConGrl.setText(" Consulta ");
        ConGrl.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConGrlActionPerformed(evt);
            }
        });

        Registro1.setText("Registro");
        Registro1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Registro1ActionPerformed(evt);
            }
        });
        Registro1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                Registro1KeyPressed(evt);
            }
        });

        Alumno1.setForeground(new java.awt.Color(255, 255, 255));
        Alumno1.setText("Alumno");

        Personal1.setForeground(new java.awt.Color(255, 255, 255));
        Personal1.setText("Personal");
        Personal1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Personal1ActionPerformed(evt);
            }
        });

        HClin1.setText("Modificaciones");
        HClin1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HClin1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/perosnal.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/almunaa.png"))); // NOI18N

        salida1.setText("Salir");
        salida1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salida1ActionPerformed(evt);
            }
        });

        ConGrl1.setText(" Consulta ");
        ConGrl1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConGrl1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro2.setText("Registro");
        Registro2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Registro2ActionPerformed(evt);
            }
        });
        Registro2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                Registro2KeyPressed(evt);
            }
        });

        Alumno2.setForeground(new java.awt.Color(255, 255, 255));
        Alumno2.setText("Alumno");

        Personal2.setForeground(new java.awt.Color(255, 255, 255));
        Personal2.setText("Personal");
        Personal2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Personal2ActionPerformed(evt);
            }
        });

        HClin2.setText("Modificaciones");
        HClin2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HClin2ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/perosnal.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/almunaa.png"))); // NOI18N

        salida2.setText("Salir");
        salida2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salida2ActionPerformed(evt);
            }
        });

        ConGrl2.setText(" Consulta ");
        ConGrl2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConGrl2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/wallpaper.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Alumno2)
                        .addGap(203, 203, 203)
                        .addComponent(Personal2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Registro2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(ConGrl2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(HClin2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(salida2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alumno2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Personal2)))
                .addGap(28, 28, 28)
                .addComponent(Registro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ConGrl2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(HClin2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(salida2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RegistroActionPerformed
    {//GEN-HEADEREND:event_RegistroActionPerformed
        Registro newFrame = new Registro();
        newFrame.setVisible(true);
    }//GEN-LAST:event_RegistroActionPerformed

    private void RegistroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_RegistroKeyPressed
    {//GEN-HEADEREND:event_RegistroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroKeyPressed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PersonalActionPerformed
    {//GEN-HEADEREND:event_PersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalActionPerformed

    private void HClinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HClinActionPerformed
    {//GEN-HEADEREND:event_HClinActionPerformed
        HistClinico newFrame =new HistClinico();
        newFrame.setVisible(true);
    }//GEN-LAST:event_HClinActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salidaActionPerformed
    {//GEN-HEADEREND:event_salidaActionPerformed
        this.dispose();
    }//GEN-LAST:event_salidaActionPerformed

    private void ConGrlActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConGrlActionPerformed
    {//GEN-HEADEREND:event_ConGrlActionPerformed
        Consultas newFrame = new Consultas();
        newFrame.setVisible(true);
    }//GEN-LAST:event_ConGrlActionPerformed

    private void Registro1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Registro1ActionPerformed
    {//GEN-HEADEREND:event_Registro1ActionPerformed
        Registro newFrame = new Registro();
        newFrame.setVisible(true);
    }//GEN-LAST:event_Registro1ActionPerformed

    private void Registro1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_Registro1KeyPressed
    {//GEN-HEADEREND:event_Registro1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registro1KeyPressed

    private void Personal1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Personal1ActionPerformed
    {//GEN-HEADEREND:event_Personal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Personal1ActionPerformed

    private void HClin1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HClin1ActionPerformed
    {//GEN-HEADEREND:event_HClin1ActionPerformed
        HistClinico newFrame =new HistClinico();
        newFrame.setVisible(true);
    }//GEN-LAST:event_HClin1ActionPerformed

    private void salida1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salida1ActionPerformed
    {//GEN-HEADEREND:event_salida1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salida1ActionPerformed

    private void ConGrl1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConGrl1ActionPerformed
    {//GEN-HEADEREND:event_ConGrl1ActionPerformed
        Consultas newFrame = new Consultas();
        newFrame.setVisible(true);
    }//GEN-LAST:event_ConGrl1ActionPerformed

    private void Registro2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Registro2ActionPerformed
    {//GEN-HEADEREND:event_Registro2ActionPerformed
        Registro newFrame = new Registro();
        newFrame.setVisible(true);
    }//GEN-LAST:event_Registro2ActionPerformed

    private void Registro2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_Registro2KeyPressed
    {//GEN-HEADEREND:event_Registro2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registro2KeyPressed

    private void Personal2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Personal2ActionPerformed
    {//GEN-HEADEREND:event_Personal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Personal2ActionPerformed

    private void HClin2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HClin2ActionPerformed
    {//GEN-HEADEREND:event_HClin2ActionPerformed
        HistClinico newFrame =new HistClinico();
        newFrame.setVisible(true);
    }//GEN-LAST:event_HClin2ActionPerformed

    private void salida2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salida2ActionPerformed
    {//GEN-HEADEREND:event_salida2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salida2ActionPerformed

    private void ConGrl2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConGrl2ActionPerformed
    {//GEN-HEADEREND:event_ConGrl2ActionPerformed
        Consultas newFrame = new Consultas();
        newFrame.setVisible(true);
    }//GEN-LAST:event_ConGrl2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PagP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PagP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PagP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PagP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PagP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Alumno;
    private javax.swing.JCheckBox Alumno1;
    private javax.swing.JCheckBox Alumno2;
    private javax.swing.JButton ConGrl;
    private javax.swing.JButton ConGrl1;
    private javax.swing.JButton ConGrl2;
    private javax.swing.JButton HClin;
    private javax.swing.JButton HClin1;
    private javax.swing.JButton HClin2;
    private javax.swing.JCheckBox Personal;
    private javax.swing.JCheckBox Personal1;
    private javax.swing.JCheckBox Personal2;
    private javax.swing.JButton Registro;
    private javax.swing.JButton Registro1;
    private javax.swing.JButton Registro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton salida;
    private javax.swing.JButton salida1;
    private javax.swing.JButton salida2;
    // End of variables declaration//GEN-END:variables
}
